name: CI

on:
  - pull_request

jobs:
  yaml-lint:
    runs-on: ubuntu-latest

    name: 'Lint: Yaml'

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Run yamllint
        uses: karancode/yamllint-github-action@v2.0.0
        with:
          yamllint_file_or_dir: '.'
          yamllint_strict: true
          yamllint_config_filepath: config/yamllint/config

  ruby-lint:
    runs-on: ubuntu-latest

    name: 'Lint: Ruby'

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: RuboCop Linter Action
        uses: andrewmcodes/rubocop-linter-action@v3.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
