name: CI

on:
  push:
    branches: [master]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Release Please
        uses: google-github-actions/release-please-action@v3
        with:
          token: '${{ secrets.RELEASE_TOKEN }}'
          release-type: simple
          package-name: dotfiles
