name: CI

on:
  - pull_request

jobs:
  yaml-lint:
    runs-on: ubuntu-latest

    name: 'Lint: Yaml'

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run yamllint
        uses: karancode/yamllint-github-action@v2.0.0
        with:
          yamllint_file_or_dir: '.'
          yamllint_strict: true
          yamllint_config_filepath: config/yamllint/config

  ruby-lint:
    runs-on: ubuntu-latest

    name: 'Lint: Ruby'

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: RuboCop Linter Action
        uses: andrewmcodes/rubocop-linter-action@v3.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  shell-lint:
    runs-on: ubuntu-latest

    name: 'Lint: Shell'

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: ShellCheck
        uses: ludeeus/action-shellcheck@b2bbefc2e6b9dcbc6355b85e366c9e55bf8d57e1
        with:
          ignore_paths: './iterm/TerminalVim.app/'
          ignore_names: '*/**/*.zsh zshrc'
