name: CI

on:
  push:
    branches: [ master ]
 
jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'chore(release):')"
    steps:
    - name: Checkout project
      uses: actions/checkout@v3
      
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'
        cache: 'npm'
        
    - name: Install dependencies with Yarn
      run: yarn install
      
    - name: Bump version and update changelog
      run: yarn release
    
    - name: Publish
      run: git push origin master
